name: invoice
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.3.1
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  google_fonts: ^2.3.1
  device_preview: ^1.0.0
  animated_text_kit: ^4.2.1
  pdf: ^3.7.4
  signature: ^5.0.0
  intl: ^0.17.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  image_gallery_saver: ^1.7.1
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
#
#  fonts:
#    - family: AppIcons
#      fonts:
#        - asset: assets/icons/AppIcons.ttf
#
#    - family: Mulish
#      fonts:
#        - asset: assets/fonts/Mulish-Black.ttf
